import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_raio.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bem vindo a</h1>
        <a href="https://site-raio.vercel.app/">
          <Image src="/logo_raio.png" alt="Logo" width={500} height={500} />
        </a>

        <button  className={styles.button} ><a href="login" >Acesso Restrito Raio Digital</a>.</button>

        <p className={styles.description}>
          Em breve nosso SITE !<code className={styles.code}></code>
        </p>
      </main>                
    </div>
  )
}
