import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo a           
        </h1>
        <a href="https://site-raio.vercel.app/">
          <Image src="/logo_raio.png" alt="Logo" width={500} height={500} />
          </a>

        <p className={styles.description}>
        Em breve nosso SITE{' '}
          <code className={styles.code}></code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a href="https://site-raio.vercel.app/" target="_blank" rel="noopener noreferrer">
          Designer by {" "} 
          <Image src="/logo_raio.png" alt="Logo" width={50} height={50} />
          <span className={styles.logo}>            
          </span>
        </a>
      </footer>
    </div>
  );
}
